# Generated by Django 2.2.7 on 2019-11-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nxtwatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('movieid', models.TextField(db_column='movieId', primary_key=True, serialize=False)),
                ('imdbid', models.TextField(blank=True, db_column='imdbId', null=True)),
                ('tmdbid', models.TextField(blank=True, db_column='tmdbId', null=True)),
            ],
            options={
                'db_table': 'links',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movieid', models.IntegerField(db_column='movieId', primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('genres', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, db_column='userId', null=True)),
                ('movieid', models.IntegerField(blank=True, db_column='movieId', null=True)),
                ('rating', models.TextField(blank=True, null=True)),
                ('timestamp', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ratings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, db_column='userId', null=True)),
                ('movieid', models.IntegerField(blank=True, db_column='movieId', null=True)),
                ('tag', models.TextField(blank=True, null=True)),
                ('timestamp', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tags',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
