# Generated by Django 2.2.7 on 2019-11-23 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nxtwatch', '0002_auto_20191123_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='movieid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nxtwatch.Movies'),
        ),
    ]
