# Generated by Django 2.2.6 on 2019-11-10 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nxtwatch', '0002_auto_20191109_0629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ratings',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'managed': False},
        ),
    ]
