# Generated by Django 2.2.7 on 2019-11-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nxtwatch', '0003_auto_20191112_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='userid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
