# Generated by Django 2.2.7 on 2019-11-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nxtwatch', '0003_auto_20191123_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='movieid',
            field=models.IntegerField(),
        ),
    ]
