# Generated by Django 2.2.7 on 2019-11-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nxtwatch', '0004_auto_20191123_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
